// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/04/2026, 22:23:23
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Matheus/projeto_clinica/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Matheus/projeto_clinica/frontend/stores/**/*.{js,ts,mjs}","C:/Users/Matheus/projeto_clinica/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Matheus/projeto_clinica/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Matheus/projeto_clinica/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Matheus/projeto_clinica/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;